// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogowanieadminTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logowanieadmin() {
    driver.get("http://demo.mrbuggy2.testarena.pl/zaloguj");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@tc2014.pl");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("12qwAS");
    driver.findElement(By.cssSelector(".tc-form")).click();
    driver.findElement(By.id("login")).click();
    driver.findElement(By.cssSelector(".content_title")).click();
    assertThat(driver.findElement(By.cssSelector(".content_title")).getText(), is("KOKPIT"));
    driver.findElement(By.linkText("Wyloguj")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("WITAJ TESTERZE!"));
    driver.findElement(By.cssSelector("h1")).click();
  }
}
